sources = [
    ("https://www.kommersant.ru/RSS/section-politics.xml", "политика"),
    ("https://russian.rt.com/rss/news", "политика"),
    ("https://www.interfax.ru/rss.asp", "экономика"),
    ("https://tass.ru/rss/v2.xml", "мир"),
    ("https://www.rt.com/rss/news/", "мир"),
    ("https://habr.com/ru/rss/articles/", "технологии"),
    ("https://www.cnews.ru/inc/rss/news.xml", "технологии"),
    ("https://www.mk.ru/rss/news/index.xml", "происшествия"),
    ("https://life.ru/xml/feed.xml", "происшествия"),
    ("https://www.proekt.media/feed/", "происшествия"),
    ("https://www.kommersant.ru/RSS/section-business.xml", "бизнес"),
    ("https://www.forbes.ru/newrss.xml", "бизнес"),
    ("https://nplus1.ru/rss", "наука"),
    ("https://www.sostav.ru/rss/", "медиа"),
    ("https://lenta.ru/rss/news", "общество"),
    ("https://www.gazeta.ru/export/rss/social.xml", "общество"),
    ("https://takiedela.ru/feed/", "общество"),
]
